### ISSUE TITLE
Inverted text

### ISSUE THREAD

**Issue by Jonic** [RaspberryPiFoundation/sauce-design-system#35]
We need a new utility that will allow for light-on-dark text.

See `src/utilities/_screen-reader-only.scss` for an existing utility classes. With this approach we can apply it directly in Sass with the mixin, or in the HTML with the attribute. I chose `sauce-` attributes for utilities so they sit outside the realms of CSS classes, which should be specific to the component.

**Comment by iamkeir** [comment]
@Jonic Can be closed?
